version: 1
disable_existing_loggers: False

formatters:
  botFormatter:
    format: "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s"
    datefmt: "%d/%b/%Y %H:%M:%S"

handlers:
  consoleHandler:
    class: logging.StreamHandler
    level: INFO
    formatter: botFormatter
    stream: ext://sys.stdout

  fileHandler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: botFormatter
    filename: bot.log
    mode: w
    maxBytes: 5242880  # 5 MB
    backupCount: 2

loggers:
  root:
    level: DEBUG
    handlers: [consoleHandler, fileHandler]
    propagate: no